canton {
  participants {
    buyerParticipant {
      storage.type = memory
      ledger-api {
        address = "0.0.0.0"
        port = 5021
      }
      http-ledger-api {
        address = "0.0.0.0"
        port = 5023
      }
      admin-api {
        address = "0.0.0.0"
        port = 5022
      }
    }
  }

  remote-domains {
    domain0 {
      public-api {
        address = "domain"
        port = 5018
      }
      admin-api {
        address = "domain"
        port = 5019
      }
    }
  }
}
