canton {
  participants {
    issuerParticipant {
      storage.type = memory
      ledger-api {
        address = "0.0.0.0"
        port = 5031
      }
      http-ledger-api {
        address = "0.0.0.0"
        port = 5033
      }
      admin-api {
        address = "0.0.0.0"
        port = 5032
      }
    }
  }

  remote-domains {
    domain0 {
      public-api {
        address = "domain"
        port = 5018
      }
      admin-api {
        address = "domain"
        port = 5019
      }
    }
  }
}
