canton {
  participants {
    sellerParticipant {
      storage.type = memory
      ledger-api {
        address = "0.0.0.0"
        port = 5011
      }
      http-ledger-api {
        address = "0.0.0.0"
        port = 5013
      }
      admin-api {
        address = "0.0.0.0"
        port = 5012
      }
    }
  }

  remote-domains {
    domain0 {
      public-api {
        address = "domain"
        port = 5018
      }
      admin-api {
        address = "domain"
        port = 5019
      }
    }
  }
}
