events {}

http {
  map $http_x_ledger_party $json_api_upstream {
    default http://seller-participant:5013;
    Seller http://seller-participant:5013;
    SellerAgent http://seller-participant:5013;
    Buyer http://buyer-participant:5023;
    BuyerAgent http://buyer-participant:5023;
    Company http://issuer-participant:5033;
  }

  server {
    listen 7575;
    server_name _;

    location / {
      proxy_pass $json_api_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Ledger-Party $http_x_ledger_party;
      proxy_set_header Authorization $http_authorization;
    }
  }
}
